[host_form_worker]
name = "host-form-worker"
main = "./workers/host-form-worker.js"
compatibility_date = "2025-04-24"

[contact_form_worker]
name = "contact-form-worker"
main = "./workers/contact-form-worker.js"
compatibility_date = "2025-04-24"
