name = "peoples-elbow"
compatibility_date = "2025-04-24"
main = "./workers/host-form-worker.js"

# Email Routing binding
[[send_email]]
name = "MAIL"
destination_address = "peoples.elbow.massage@gmail.com"
