name = "changelog-reader"
compatibility_date = "2025-04-24"
main = "./changelog-reader-worker.js"

# D1 Database binding for Changelog
[[d1_databases]]
binding = "CHANGELOG_DB"
database_name = "peoples-elbow-changelog"
database_id = "525c3570-af7a-4939-9d3c-d9beafab9cf3"
preview_database_id = "CHANGELOG_DB" # For local development
