name: Update Version Data and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'js/version-data.js'  # Prevent loops when only version data changes

permissions:
  contents: write  # Permission to write to repository

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Need full history for commit count
      
      # Check if this is already a version update commit
      - name: Check commit type
        id: commit_check
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Latest commit message: $COMMIT_MSG"
          if [[ "$COMMIT_MSG" == *"update version data [skip ci]"* ]]; then
            echo "This is an automated version update, skipping"
            echo "should_update=false" >> $GITHUB_OUTPUT
          else
            echo "This is a regular commit, updating version data"
            echo "should_update=true" >> $GITHUB_OUTPUT
          fi
      
      # Skip the rest if this is already a version update commit
      - name: Setup Node.js
        if: steps.commit_check.outputs.should_update != 'false'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      # THIS IS THE KEY FIX - Pre-generate version info before the main script
      - name: Pre-process commit count for current commit
        if: steps.commit_check.outputs.should_update != 'false'
        run: |
          # Get raw commit count including the current commit
          TOTAL_COMMITS=$(git rev-list --count HEAD)
          
          # Save to a temporary file to be used by the version generator
          echo "$TOTAL_COMMITS" > .current-commit-count
          
          # Debug output
          echo "Total commits (including current): $TOTAL_COMMITS"
          echo "Saved current commit count for version generation"
      
      # Modified generate-version-data.js will read from .current-commit-count if it exists
      - name: Update generate-version-data.js to be aware of current commit
        if: steps.commit_check.outputs.should_update != 'false'
        run: |
          # Add code to read from the commit count file if it exists
          sed -i '/function getCommitCount/a\  // Check for pre-counted commit value that includes current commit\n  try {\n    const preCountedCommits = require(\'fs\').readFileSync(\'.current-commit-count\', \'utf8\').trim();\n    if (preCountedCommits && !isNaN(parseInt(preCountedCommits))) {\n      console.log(`Using pre-counted commit value: ${preCountedCommits}`);\n      return parseInt(preCountedCommits);\n    }\n  } catch (e) {\n    console.log("No pre-counted commit value found, calculating normally");\n  }' generate-version-data.js
      
      - name: Generate version data
        if: steps.commit_check.outputs.should_update != 'false'
        run: |
          # Run with extra debugging
          echo "Running version data generation with current commit awareness"
          node generate-version-data.js
          echo "Version data generation complete"
      
      - name: Check if version was updated
        id: version_check
        if: steps.commit_check.outputs.should_update != 'false'
        run: |
          if [[ $(git status --porcelain js/version-data.js | wc -l) -gt 0 ]]; then
            echo "Version data was updated"
            echo "updated=true" >> $GITHUB_OUTPUT
            
            # Log the new version number for debugging
            NEW_VERSION=$(grep -o '"version": "[0-9]*"' js/version-data.js | grep -o '[0-9]*')
            echo "New version number: $NEW_VERSION"
          else
            echo "No changes to version data"
            echo "updated=false" >> $GITHUB_OUTPUT
          fi
        
      - name: Commit and push if changed
        if: steps.commit_check.outputs.should_update != 'false' && steps.version_check.outputs.updated == 'true'
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add js/version-data.js
          git commit -m "chore: update version data [skip ci]"
          git push
          # Add a short delay to ensure changes are registered before GitHub Pages builds
          sleep 5
