name: Update Version Data

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'js/version-data.js'  # Prevent loops when only version data changes

permissions:
  contents: write  # Permission to write to repository

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Need full history for commit count
      
      # Check if this is already a version update commit
      - name: Check commit type
        id: commit_check
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Latest commit message: $COMMIT_MSG"
          if [[ "$COMMIT_MSG" == *"update version data [skip ci]"* ]]; then
            echo "This is an automated version update, skipping"
            echo "should_update=false" >> $GITHUB_OUTPUT
          else
            echo "This is a regular commit, updating version data"
            echo "should_update=true" >> $GITHUB_OUTPUT
          fi
      
      # Skip the rest if this is already a version update commit
      - name: Setup Node.js
        if: steps.commit_check.outputs.should_update != 'false'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Generate version data
        if: steps.commit_check.outputs.should_update != 'false'
        run: node generate-version-data.js
      
      - name: Check if version was updated
        id: version_check
        if: steps.commit_check.outputs.should_update != 'false'
        run: |
          if [[ $(git status --porcelain js/version-data.js | wc -l) -gt 0 ]]; then
            echo "Version data was updated"
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to version data"
            echo "updated=false" >> $GITHUB_OUTPUT
          fi
        
      - name: Commit and push if changed
        if: steps.commit_check.outputs.should_update != 'false' && steps.version_check.outputs.updated == 'true'
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add js/version-data.js
          git commit -m "chore: update version data [skip ci]"
          git push
          # Add a short delay to ensure changes are registered before GitHub Pages builds
          sleep 5
